USE [master]
GO
/****** Object:  Database [WebBanHang_Lab03]    Script Date: 18/05/2025 10:59:17 ******/
CREATE DATABASE [WebBanHang_Lab03]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebBanHang_Lab03', FILENAME = N'D:\Program Files\MSSQL16.SQLEXPRESS\MSSQL\DATA\WebBanHang_Lab03.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebBanHang_Lab03_log', FILENAME = N'D:\Program Files\MSSQL16.SQLEXPRESS\MSSQL\DATA\WebBanHang_Lab03_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [WebBanHang_Lab03] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebBanHang_Lab03].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WebBanHang_Lab03] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET ARITHABORT OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [WebBanHang_Lab03] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WebBanHang_Lab03] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WebBanHang_Lab03] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET  ENABLE_BROKER 
GO
ALTER DATABASE [WebBanHang_Lab03] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WebBanHang_Lab03] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [WebBanHang_Lab03] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [WebBanHang_Lab03] SET  MULTI_USER 
GO
ALTER DATABASE [WebBanHang_Lab03] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WebBanHang_Lab03] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WebBanHang_Lab03] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WebBanHang_Lab03] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WebBanHang_Lab03] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [WebBanHang_Lab03] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [WebBanHang_Lab03] SET QUERY_STORE = ON
GO
ALTER DATABASE [WebBanHang_Lab03] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [WebBanHang_Lab03]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 18/05/2025 10:59:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 18/05/2025 10:59:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductImages]    Script Date: 18/05/2025 10:59:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductImages](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Url] [nvarchar](max) NOT NULL,
	[ProductId] [int] NOT NULL,
 CONSTRAINT [PK_ProductImages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 18/05/2025 10:59:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[ImageUrl] [nvarchar](max) NULL,
	[CategoryId] [int] NOT NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250517143943_InitMigration', N'8.0.3')
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250517235539_AddCol_DesToCategoryTable', N'8.0.3')
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250518000446_DropCol_DesToCategoryTable', N'8.0.3')
GO
SET IDENTITY_INSERT [dbo].[Categories] ON 
GO
INSERT [dbo].[Categories] ([Id], [Name]) VALUES (1, N'Lập trình')
GO
INSERT [dbo].[Categories] ([Id], [Name]) VALUES (2, N'Văn hóa')
GO
SET IDENTITY_INSERT [dbo].[Categories] OFF
GO
SET IDENTITY_INSERT [dbo].[Products] ON 
GO
INSERT [dbo].[Products] ([Id], [Name], [Price], [Description], [ImageUrl], [CategoryId]) VALUES (1, N'Lập trình C', CAST(234000.00 AS Decimal(18, 2)), N'Sách bộ môn CNPM', NULL, 1)
GO
INSERT [dbo].[Products] ([Id], [Name], [Price], [Description], [ImageUrl], [CategoryId]) VALUES (2, N'Tôi tài giỏi bạn  cũng thế', CAST(129900.00 AS Decimal(18, 2)), N'Sách văn hóa', NULL, 2)
GO
INSERT [dbo].[Products] ([Id], [Name], [Price], [Description], [ImageUrl], [CategoryId]) VALUES (3, N'Nhà Giả Kim', CAST(123000.00 AS Decimal(18, 2)), N'123', NULL, 2)
GO
SET IDENTITY_INSERT [dbo].[Products] OFF
GO
/****** Object:  Index [IX_ProductImages_ProductId]    Script Date: 18/05/2025 10:59:17 ******/
CREATE NONCLUSTERED INDEX [IX_ProductImages_ProductId] ON [dbo].[ProductImages]
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Products_CategoryId]    Script Date: 18/05/2025 10:59:17 ******/
CREATE NONCLUSTERED INDEX [IX_Products_CategoryId] ON [dbo].[Products]
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ProductImages]  WITH CHECK ADD  CONSTRAINT [FK_ProductImages_Products_ProductId] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProductImages] CHECK CONSTRAINT [FK_ProductImages_Products_ProductId]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Categories_CategoryId] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Categories_CategoryId]
GO
USE [master]
GO
ALTER DATABASE [WebBanHang_Lab03] SET  READ_WRITE 
GO
